"""initial ingestion schema

Revision ID: 0aa60702698f
Revises: 
Create Date: 2026-08-20 00:37:06.240881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0aa60702698f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('city_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('city_id')
    )
    op.create_table('extractions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_ref', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('extracted_from', sa.String(length=8), nullable=True),
    sa.Column('is_useful', sa.Boolean(), nullable=False),
    sa.Column('is_promotional', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('place_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('youtube', 'rednote', 'places', 'gemini')", name='ck_source_source'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_ref', 'prompt_version', 'model', name='uq_extraction_ref_version')
    )
    op.create_table('rednote_posts',
    sa.Column('note_id', sa.String(length=64), nullable=False),
    sa.Column('xsec_token', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('image_urls', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('ip_location', sa.String(length=64), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_table('youtube_videos',
    sa.Column('video_id', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('captions', sa.String(length=16), nullable=True),
    sa.Column('lang', sa.String(length=16), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_table('ingest_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('city_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_task_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("kind IN ('city_ingest', 'trip_planning')", name='ck_kind_runkind'),
    sa.CheckConstraint("status IN ('pending', 'running', 'done', 'failed', 'needs_credentials')", name='ck_status_runstatus'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('uq_run_active_city', 'ingest_runs', ['city_id'], unique=True, postgresql_where=sa.text("kind = 'city_ingest' AND status IN ('pending', 'running')"))
    op.create_table('places',
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('city_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('primary_type', sa.String(length=120), nullable=True),
    sa.Column('resolved_from_name', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('confidence_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidence IN ('high', 'medium', 'low')", name='ck_confidence_confidence'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], ),
    sa.PrimaryKeyConstraint('place_id')
    )
    op.create_index('ix_places_city', 'places', ['city_id'], unique=False)
    op.create_table('ingest_tasks',
    sa.Column('task_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=16), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("error_code IN ('transient', 'rate_limited', 'credentials', 'quota', 'permanent')", name='ck_error_code_errorcode'),
    sa.CheckConstraint("kind IN ('youtube.search', 'youtube.extract', 'rednote.search', 'rednote.fetch', 'rednote.extract', 'rednote.ocr', 'places.resolve')", name='ck_kind_taskkind'),
    sa.CheckConstraint("source IN ('youtube', 'rednote', 'places', 'gemini')", name='ck_source_source'),
    sa.CheckConstraint("status IN ('pending', 'running', 'done', 'failed', 'skipped', 'blocked')", name='ck_status_taskstatus'),
    sa.ForeignKeyConstraint(['run_id'], ['ingest_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('run_id', 'dedupe_key', name='uq_task_run_dedupe')
    )
    op.create_index('ix_task_claim', 'ingest_tasks', ['status', 'run_after', 'task_id'], unique=False)
    op.create_index('ix_task_lease', 'ingest_tasks', ['status', 'locked_at'], unique=False)
    op.create_index('ix_task_run_kind', 'ingest_tasks', ['run_id', 'kind', 'status'], unique=False)
    op.create_table('place_mentions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_ref', sa.String(length=64), nullable=False),
    sa.Column('name_as_written', sa.Text(), nullable=True),
    sa.Column('why_go', sa.Text(), nullable=True),
    sa.Column('dish', sa.Text(), nullable=True),
    sa.Column('quoted_price', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('source_timestamp', sa.String(length=16), nullable=True),
    sa.Column('extracted_from', sa.String(length=8), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("extracted_from IN ('text', 'image')", name='ck_extracted_from_extractedfrom'),
    sa.CheckConstraint("sentiment IN ('recommended', 'mixed', 'not_recommended')", name='ck_sentiment_sentiment'),
    sa.CheckConstraint("source IN ('youtube', 'rednote', 'places', 'gemini')", name='ck_source_source'),
    sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id', 'source', 'source_ref', name='uq_mention_place_source_ref')
    )
    op.create_index('ix_mentions_place', 'place_mentions', ['place_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mentions_place', table_name='place_mentions')
    op.drop_table('place_mentions')
    op.drop_index('ix_task_run_kind', table_name='ingest_tasks')
    op.drop_index('ix_task_lease', table_name='ingest_tasks')
    op.drop_index('ix_task_claim', table_name='ingest_tasks')
    op.drop_table('ingest_tasks')
    op.drop_index('ix_places_city', table_name='places')
    op.drop_table('places')
    op.drop_index('uq_run_active_city', table_name='ingest_runs', postgresql_where=sa.text("kind = 'city_ingest' AND status IN ('pending', 'running')"))
    op.drop_table('ingest_runs')
    op.drop_table('youtube_videos')
    op.drop_table('rednote_posts')
    op.drop_table('extractions')
    op.drop_table('cities')
    # ### end Alembic commands ###
