"""add ingest_tasks.started_at

Revision ID: 308b47446161
Revises: 6faab6b6e804
Create Date: 2026-08-27 12:08:44.466767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '308b47446161'
down_revision: Union[str, Sequence[str], None] = '6faab6b6e804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingest_tasks', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingest_tasks', 'started_at')
    # ### end Alembic commands ###
