"""add users, user_trips and sessions

Revision ID: 6637dd5a7693
Revises: f2b9c07d41ae
Create Date: 2026-09-11 23:57:19.034190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6637dd5a7693'
down_revision: Union[str, Sequence[str], None] = 'f2b9c07d41ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Trips predate users, so there is no owner to backfill from. itinerary_items and
    # trip_dismissals cascade; trip_plan runs carry a trip_id in the task payload with no FK, so a
    # pending route.plan task would otherwise wake up pointing at a trip that is gone. City-scoped
    # data is untouched: places and mentions stay, so a re-created trip is warm immediately.
    op.execute("DELETE FROM ingest_runs WHERE kind = 'trip_plan'")
    op.execute("DELETE FROM trips")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_table('sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('user_trips',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'trip_id')
    )
    op.create_index('ix_user_trips_user', 'user_trips', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema. The deleted trips do not come back."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_trips_user', table_name='user_trips')
    op.drop_table('user_trips')
    op.drop_table('sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
