"""add throttle_calls

Revision ID: 77bd2e84b0a7
Revises: 2ddca817ffe5
Create Date: 2026-08-21 11:53:30.603395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77bd2e84b0a7'
down_revision: Union[str, Sequence[str], None] = '2ddca817ffe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('throttle_calls',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_throttle_domain_time', 'throttle_calls', ['domain', 'called_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_throttle_domain_time', table_name='throttle_calls')
    op.drop_table('throttle_calls')
    # ### end Alembic commands ###
