"""add itinerary items and place hours

Revision ID: aa7111c8290a
Revises: 77bd2e84b0a7
Create Date: 2026-08-24 12:36:59.976262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa7111c8290a'
down_revision: Union[str, Sequence[str], None] = '77bd2e84b0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day_index >= 0', name='ck_itinerary_day'),
    sa.CheckConstraint('duration_min > 0', name='ck_itinerary_duration'),
    sa.CheckConstraint('position >= 0', name='ck_itinerary_position'),
    sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'place_id', name='uq_itinerary_trip_place')
    )
    op.create_index('ix_itinerary_trip_day', 'itinerary_items', ['trip_id', 'day_index', 'position'], unique=False)
    op.create_table('place_hours',
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('periods', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('weekday_descriptions', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('utc_offset_minutes', sa.Integer(), nullable=True),
    sa.Column('has_hours', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], ),
    sa.PrimaryKeyConstraint('place_id')
    )
    op.create_table('trip_dismissals',
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trip_id', 'place_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_dismissals')
    op.drop_table('place_hours')
    op.drop_index('ix_itinerary_trip_day', table_name='itinerary_items')
    op.drop_table('itinerary_items')
    # ### end Alembic commands ###
