"""give user_trips a role

Revision ID: c551f84a2e7d
Revises: 6637dd5a7693
Create Date: 2026-09-17 15:06:01.331218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c551f84a2e7d'
down_revision: Union[str, Sequence[str], None] = '6637dd5a7693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema. Every row that exists is a trip's creator, so every row is its owner."""
    op.add_column('user_trips', sa.Column('role', sa.String(length=16), nullable=True))
    op.execute("UPDATE user_trips SET role = 'owner' WHERE role IS NULL")
    op.alter_column('user_trips', 'role', nullable=False)
    op.create_index('uq_user_trips_owner', 'user_trips', ['trip_id'], unique=True, postgresql_where=sa.text("role = 'owner'"))
    op.create_check_constraint('ck_role_triprole', 'user_trips', "role IN ('owner', 'editor', 'viewer')")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_role_triprole', 'user_trips', type_='check')
    op.drop_index('uq_user_trips_owner', table_name='user_trips', postgresql_where=sa.text("role = 'owner'"))
    op.drop_column('user_trips', 'role')
    # ### end Alembic commands ###
